### PR TITLE
Add C# to the SQLite challenge

### PR DESCRIPTION
**Pull request by bert2**
A little christmas present 😄

### CODE REVIEW

**Comment by bert2** [comment]
Ok, I had to run `make compile` on a proper linux file system for `FileUtils.chmod(0755, path)` to actually change something. I'm only using the Windows Subsystem for Linux (WSL2) where `chmod` has no effect when executed on a windows file system.

**Comment by rohitpaulk** [comment]
I'll look at the build failures here, for some reason Rust builds seem to be taking far longer (45m) than expected (5m).

**Comment by rohitpaulk** [comment]
Quick update here - this is still on my list, should get to it soon. Haven't been able to look at this yet because we're busy working on supporting customizable dependencies currently.

**Comment by bert2** [comment]
No worries, @rohitpaulk.

By the way there is another possibility how to organize the dependencies here. The .csproj could basically act like a package.json/cargo.toml to force/monitor dependencies in case that's desired. Let me know if I can assist in any way.

**Comment by rohitpaulk** [comment]
Sorry, dropped the ball here - we were focused on other stuff for a while but are now getting back to expanding language support. 

Recently added the option to "request" language support for each challenge, and C# is one of the most requested languages so far! 

Screenshot 2022-05-12 at 19 13 22

I'm going to add C# support to the Redis challenge first since there's a smaller code footprint in terms of starter code, and then come back and revive this PR. Thank you for all the hard work, @bert2!

**Comment by bert2** [comment]
@rohitpaulk Nice! I'm looking forward to doing the redis challenge with C# 🙂

**Comment by bert2** [comment]
I merged master into the PR, fixed some conflicts, and aligned the C# project structure with how you did it in the redis starter.

**Comment by rohitpaulk** [comment]
@bert2 awesome, thank you so much! Aiming to get this out today 🙂 Redis support for C# is live now if you'd like to try btw!

**Pull request merged**
