### PR TITLE
Add sha-1 crate for Git - Rust

### PR DESCRIPTION
**Pull request by rohitpaulk**
Ref: https://discord.com/channels/673463293901537291/705313871245869139/723487117300334622

Thanks to @bert2 for helping out with this 🥳

### CODE REVIEW

**Comment by bert2** [comment]
Thanks! This reminds me that the [`bytes` crate](https://crates.io/crates/bytes) is also needed. The reqwest crate uses it to wrap the contents of responses and it makes life much easier when parsing byte data.

**Comment by rohitpaulk** [comment]
Ah, got it. Adding..

**Comment by rohitpaulk** [comment]
@bert2 Looks like `bytes` is already included in the list of dependencies for `reqwest`. Does it have to be explicitly included in `Cargo.toml` too? It's in `Cargo.lock` here: https://github.com/codecrafters-io/languages/blob/5746db439eae64c99189ce464509f0d4a747f2b1/compiled_starters/git-starter-rust/Cargo.lock#L39-L43

**Comment by bert2** [comment]
Yes, you have to add it explicitly to the dependencies if you want to use it in your code.

**Comment by rohitpaulk** [comment]
Ah, okay got it 👍

**Pull request merged**
