### PR TITLE
Add Rust Docker starter

### PR DESCRIPTION
**Pull request by byarr**
My first attempt at a rust docker starter.

I'm neither much of a rustacean nor a docker expert. Getting the docker build to be anything like quick enough required a bit of messing about. Hopefully it works. 

I guess it would be useful to run through the challenge and see if there any deps that would be useful.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@byarr thanks so much for the PR! Going to take a look at this tomorrow.

**Comment by rohitpaulk** [comment]
@byarr just fyi, I've changed the GitHub actions configuration so that tests will run without approval (looks like a recent default that GitHub turned on automatically).

**Comment by rohitpaulk** [comment]
Looking good! I'll merge and deploy this to the early access instance today so that you can try it out @byarr. 

It's possible that we'll need more dependencies, depending on what exists in the Rust stdlib and what doesn't. We'll cross that bridge when we get to it - hard to figure this out upfront.

**Comment by byarr** [comment]
> Looking good! I'll merge and deploy this to the early access instance today so that you can try it out @byarr.
> 
> It's possible that we'll need more dependencies, depending on what exists in the Rust stdlib and what doesn't. We'll cross that bridge when we get to it - hard to figure this out upfront.

Amazing! I'll give it a go in EA and see if any deps would help.

**Pull request merged**
