### PR TITLE
Add support for redis in elixir

### PR DESCRIPTION
**Pull request by goodhamgupta**
Hi,

This PR aims to add support for Redis in elixir. I've used `mix` to create the project, and the project structure and file names are not the same as the other implementations. Let me know how I can improve this implementation! :+1:

### CODE REVIEW

**Comment by rohitpaulk** [comment]
🙏 nice! 

Thanks for the work on this, @goodhamgupta 🙂 I'll take a look at this soon.

**Comment by rohitpaulk** [comment]
@goodhamgupta looks like there are conflicts with master here, want to try resolving them?

**Comment by goodhamgupta** [comment]
@rohitpaulk I've rebased this branch and also fixed the CI :+1:

**Comment by rohitpaulk** [comment]
Screenshot 2020-07-04 at 2 36 16 PM

The Elixir logo was the toughest of the lot to make 😃

**Comment by rohitpaulk** [comment]
Hey @goodhamgupta - just wanted to let you know that the other pieces that were required for this (and the other Kotlin/Java PRs) are done now, so I'll review and merge this in this week! 🙂

**Comment by goodhamgupta** [comment]
Awesome! Thanks @rohitpaulk! :+1:

**Comment by rohitpaulk** [comment]
Made a few changes, @goodhamgupta - basically trimmed down the amount of sample code to only pass the first stage, and not suggest what the implementation should be like for further stages 🙂 Merging this in, will propagate the changes from other components shortly and make this live. Thanks for all your work!

**Pull request merged**
